apiVersion: v1
kind: Service
metadata:
  name: userapi-srv
spec:
  selector:
    name: userapi
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 31111